name: link_tattoo_manager
description: Aplicaci贸n de gesti贸n para estudios de tatuajes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

  # Backend y autenticaci贸n
  supabase_flutter: ^2.9.1

  # Almacenamiento offline
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Gesti贸n de archivos
  pdf: ^3.11.3
  share_plus: ^11.0.0

  # Notificaciones y conectividad
  flutter_local_notifications: ^19.2.1
  connectivity_plus: ^6.1.4

  # Estado y utilidades
  provider: ^6.1.5
  intl: ^0.20.2

  # UI y calendario
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/icon.png
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"